// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: drift_events.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const createDriftEvent = `-- name: CreateDriftEvent :one
INSERT INTO drift_events (
    project_id,
    snapshot_id,
    drift_type,
    container_name,
    live_value,
    declared_value,
    severity,
    ai_summary,
    fix_command
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9
)
RETURNING id, project_id, snapshot_id, drift_type, container_name, live_value, declared_value, severity, ai_summary, fix_command, alerted_at, resolved_at, created_at
`

type CreateDriftEventParams struct {
	ProjectID     uuid.UUID `json:"project_id"`
	SnapshotID    uuid.UUID `json:"snapshot_id"`
	DriftType     string    `json:"drift_type"`
	ContainerName string    `json:"container_name"`
	LiveValue     *string   `json:"live_value"`
	DeclaredValue *string   `json:"declared_value"`
	Severity      string    `json:"severity"`
	AiSummary     *string   `json:"ai_summary"`
	FixCommand    *string   `json:"fix_command"`
}

func (q *Queries) CreateDriftEvent(ctx context.Context, arg CreateDriftEventParams) (DriftEvent, error) {
	row := q.db.QueryRow(ctx, createDriftEvent,
		arg.ProjectID,
		arg.SnapshotID,
		arg.DriftType,
		arg.ContainerName,
		arg.LiveValue,
		arg.DeclaredValue,
		arg.Severity,
		arg.AiSummary,
		arg.FixCommand,
	)
	var i DriftEvent
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.SnapshotID,
		&i.DriftType,
		&i.ContainerName,
		&i.LiveValue,
		&i.DeclaredValue,
		&i.Severity,
		&i.AiSummary,
		&i.FixCommand,
		&i.AlertedAt,
		&i.ResolvedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getDriftEventByID = `-- name: GetDriftEventByID :one
SELECT id, project_id, snapshot_id, drift_type, container_name, live_value, declared_value, severity, ai_summary, fix_command, alerted_at, resolved_at, created_at
FROM drift_events
WHERE id = $1
`

func (q *Queries) GetDriftEventByID(ctx context.Context, id uuid.UUID) (DriftEvent, error) {
	row := q.db.QueryRow(ctx, getDriftEventByID, id)
	var i DriftEvent
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.SnapshotID,
		&i.DriftType,
		&i.ContainerName,
		&i.LiveValue,
		&i.DeclaredValue,
		&i.Severity,
		&i.AiSummary,
		&i.FixCommand,
		&i.AlertedAt,
		&i.ResolvedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getUnresolvedDriftEvents = `-- name: GetUnresolvedDriftEvents :many
SELECT id, project_id, snapshot_id, drift_type, container_name, live_value, declared_value, severity, ai_summary, fix_command, alerted_at, resolved_at, created_at
FROM drift_events
WHERE resolved_at IS NULL
ORDER BY created_at DESC
`

func (q *Queries) GetUnresolvedDriftEvents(ctx context.Context) ([]DriftEvent, error) {
	rows, err := q.db.Query(ctx, getUnresolvedDriftEvents)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []DriftEvent
	for rows.Next() {
		var i DriftEvent
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.SnapshotID,
			&i.DriftType,
			&i.ContainerName,
			&i.LiveValue,
			&i.DeclaredValue,
			&i.Severity,
			&i.AiSummary,
			&i.FixCommand,
			&i.AlertedAt,
			&i.ResolvedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDriftEventsByProject = `-- name: ListDriftEventsByProject :many
SELECT id, project_id, snapshot_id, drift_type, container_name, live_value, declared_value, severity, ai_summary, fix_command, alerted_at, resolved_at, created_at
FROM drift_events
WHERE project_id = $1
ORDER BY created_at DESC
LIMIT 50
`

func (q *Queries) ListDriftEventsByProject(ctx context.Context, projectID uuid.UUID) ([]DriftEvent, error) {
	rows, err := q.db.Query(ctx, listDriftEventsByProject, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []DriftEvent
	for rows.Next() {
		var i DriftEvent
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.SnapshotID,
			&i.DriftType,
			&i.ContainerName,
			&i.LiveValue,
			&i.DeclaredValue,
			&i.Severity,
			&i.AiSummary,
			&i.FixCommand,
			&i.AlertedAt,
			&i.ResolvedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markDriftEventAlerted = `-- name: MarkDriftEventAlerted :exec
UPDATE drift_events
SET alerted_at = now()
WHERE id = $1
`

func (q *Queries) MarkDriftEventAlerted(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, markDriftEventAlerted, id)
	return err
}

const resolveDriftEvent = `-- name: ResolveDriftEvent :exec
UPDATE drift_events
SET resolved_at = now()
WHERE id = $1
`

func (q *Queries) ResolveDriftEvent(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, resolveDriftEvent, id)
	return err
}

const updateDriftEventAnalysis = `-- name: UpdateDriftEventAnalysis :exec
UPDATE drift_events
SET ai_summary = $2, fix_command = $3
WHERE id = $1
`

type UpdateDriftEventAnalysisParams struct {
	ID         uuid.UUID `json:"id"`
	AiSummary  *string   `json:"ai_summary"`
	FixCommand *string   `json:"fix_command"`
}

func (q *Queries) UpdateDriftEventAnalysis(ctx context.Context, arg UpdateDriftEventAnalysisParams) error {
	_, err := q.db.Exec(ctx, updateDriftEventAnalysis, arg.ID, arg.AiSummary, arg.FixCommand)
	return err
}
