// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type DriftEvent struct {
	ID            uuid.UUID          `json:"id"`
	ProjectID     uuid.UUID          `json:"project_id"`
	SnapshotID    uuid.UUID          `json:"snapshot_id"`
	DriftType     string             `json:"drift_type"`
	ContainerName string             `json:"container_name"`
	LiveValue     *string            `json:"live_value"`
	DeclaredValue *string            `json:"declared_value"`
	Severity      string             `json:"severity"`
	AiSummary     *string            `json:"ai_summary"`
	FixCommand    *string            `json:"fix_command"`
	AlertedAt     pgtype.Timestamptz `json:"alerted_at"`
	ResolvedAt    pgtype.Timestamptz `json:"resolved_at"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
}

type Project struct {
	ID                   uuid.UUID          `json:"id"`
	Name                 string             `json:"name"`
	RepoOwner            string             `json:"repo_owner"`
	RepoName             string             `json:"repo_name"`
	RepoBranch           string             `json:"repo_branch"`
	DockerHost           string             `json:"docker_host"`
	GithubTokenEncrypted *string            `json:"github_token_encrypted"`
	AgentKeyHash         string             `json:"agent_key_hash"`
	DiscordWebhookUrl    string             `json:"discord_webhook_url"`
	CreatedAt            pgtype.Timestamptz `json:"created_at"`
	UpdatedAt            pgtype.Timestamptz `json:"updated_at"`
	UserID               *uuid.UUID         `json:"user_id"`
}

type Snapshot struct {
	ID            uuid.UUID          `json:"id"`
	ProjectID     uuid.UUID          `json:"project_id"`
	StateHash     string             `json:"state_hash"`
	LiveState     []byte             `json:"live_state"`
	DeclaredState []byte             `json:"declared_state"`
	TakenAt       pgtype.Timestamptz `json:"taken_at"`
}

type User struct {
	ID                   uuid.UUID          `json:"id"`
	Email                string             `json:"email"`
	PasswordHash         *string            `json:"password_hash"`
	CreatedAt            pgtype.Timestamptz `json:"created_at"`
	GithubID             *int64             `json:"github_id"`
	GithubLogin          string             `json:"github_login"`
	AvatarUrl            string             `json:"avatar_url"`
	GithubTokenEncrypted string             `json:"github_token_encrypted"`
}
