// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: projects.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const createProject = `-- name: CreateProject :one
INSERT INTO projects (
    name,
    repo_owner,
    repo_name,
    repo_branch,
    docker_host,
    github_token_encrypted,
    user_id
) VALUES (
    $1, $2, $3, $4, $5, $6, $7
)
RETURNING id, name, repo_owner, repo_name, repo_branch, docker_host, github_token_encrypted, discord_webhook_url, created_at, updated_at, user_id
`

type CreateProjectParams struct {
	Name                 string     `json:"name"`
	RepoOwner            string     `json:"repo_owner"`
	RepoName             string     `json:"repo_name"`
	RepoBranch           string     `json:"repo_branch"`
	DockerHost           string     `json:"docker_host"`
	GithubTokenEncrypted *string    `json:"github_token_encrypted"`
	UserID               *uuid.UUID `json:"user_id"`
}

func (q *Queries) CreateProject(ctx context.Context, arg CreateProjectParams) (Project, error) {
	row := q.db.QueryRow(ctx, createProject,
		arg.Name,
		arg.RepoOwner,
		arg.RepoName,
		arg.RepoBranch,
		arg.DockerHost,
		arg.GithubTokenEncrypted,
		arg.UserID,
	)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.RepoOwner,
		&i.RepoName,
		&i.RepoBranch,
		&i.DockerHost,
		&i.GithubTokenEncrypted,
		&i.DiscordWebhookUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.UserID,
	)
	return i, err
}

const deleteProjectForUser = `-- name: DeleteProjectForUser :execrows
DELETE FROM projects
WHERE id = $1 AND user_id = $2
`

type DeleteProjectForUserParams struct {
	ID     uuid.UUID  `json:"id"`
	UserID *uuid.UUID `json:"user_id"`
}

func (q *Queries) DeleteProjectForUser(ctx context.Context, arg DeleteProjectForUserParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteProjectForUser, arg.ID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getProjectByID = `-- name: GetProjectByID :one
SELECT id, name, repo_owner, repo_name, repo_branch, docker_host, github_token_encrypted, discord_webhook_url, created_at, updated_at, user_id
FROM projects
WHERE id = $1
`

// Unscoped lookup. Used by the scheduler and webhook (which don't have a
// user context). HTTP handlers MUST use GetProjectByIDForUser instead.
func (q *Queries) GetProjectByID(ctx context.Context, id uuid.UUID) (Project, error) {
	row := q.db.QueryRow(ctx, getProjectByID, id)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.RepoOwner,
		&i.RepoName,
		&i.RepoBranch,
		&i.DockerHost,
		&i.GithubTokenEncrypted,
		&i.DiscordWebhookUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.UserID,
	)
	return i, err
}

const getProjectByIDForUser = `-- name: GetProjectByIDForUser :one
SELECT id, name, repo_owner, repo_name, repo_branch, docker_host, github_token_encrypted, discord_webhook_url, created_at, updated_at, user_id
FROM projects
WHERE id = $1 AND user_id = $2
`

type GetProjectByIDForUserParams struct {
	ID     uuid.UUID  `json:"id"`
	UserID *uuid.UUID `json:"user_id"`
}

func (q *Queries) GetProjectByIDForUser(ctx context.Context, arg GetProjectByIDForUserParams) (Project, error) {
	row := q.db.QueryRow(ctx, getProjectByIDForUser, arg.ID, arg.UserID)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.RepoOwner,
		&i.RepoName,
		&i.RepoBranch,
		&i.DockerHost,
		&i.GithubTokenEncrypted,
		&i.DiscordWebhookUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.UserID,
	)
	return i, err
}

const listProjects = `-- name: ListProjects :many
SELECT id, name, repo_owner, repo_name, repo_branch, docker_host, github_token_encrypted, discord_webhook_url, created_at, updated_at, user_id
FROM projects
ORDER BY created_at DESC
`

// Unscoped list — only used by scheduler.LoadAllProjects on boot to
// register cron entries across every project. NOT for HTTP handlers.
func (q *Queries) ListProjects(ctx context.Context) ([]Project, error) {
	rows, err := q.db.Query(ctx, listProjects)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Project
	for rows.Next() {
		var i Project
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.RepoOwner,
			&i.RepoName,
			&i.RepoBranch,
			&i.DockerHost,
			&i.GithubTokenEncrypted,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.UserID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProjectsByRepo = `-- name: ListProjectsByRepo :many
SELECT id, name, repo_owner, repo_name, repo_branch, docker_host, github_token_encrypted, discord_webhook_url, created_at, updated_at, user_id
FROM projects
WHERE repo_owner = $1 AND repo_name = $2
`

type ListProjectsByRepoParams struct {
	RepoOwner string `json:"repo_owner"`
	RepoName  string `json:"repo_name"`
}

// Used by the GitHub webhook handler to fan out a TriggerScan to every
// project that's tracking the repo the push landed on.
func (q *Queries) ListProjectsByRepo(ctx context.Context, arg ListProjectsByRepoParams) ([]Project, error) {
	rows, err := q.db.Query(ctx, listProjectsByRepo, arg.RepoOwner, arg.RepoName)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Project
	for rows.Next() {
		var i Project
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.RepoOwner,
			&i.RepoName,
			&i.RepoBranch,
			&i.DockerHost,
			&i.GithubTokenEncrypted,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.UserID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProjectsForUser = `-- name: ListProjectsForUser :many
SELECT id, name, repo_owner, repo_name, repo_branch, docker_host, github_token_encrypted, discord_webhook_url, created_at, updated_at, user_id
FROM projects
WHERE user_id = $1
ORDER BY created_at DESC
`

func (q *Queries) ListProjectsForUser(ctx context.Context, userID *uuid.UUID) ([]Project, error) {
	rows, err := q.db.Query(ctx, listProjectsForUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Project
	for rows.Next() {
		var i Project
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.RepoOwner,
			&i.RepoName,
			&i.RepoBranch,
			&i.DockerHost,
			&i.GithubTokenEncrypted,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.UserID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateProject = `-- name: UpdateProject :one
UPDATE projects
SET
    name = $2,
    repo_owner = $3,
    repo_name = $4,
    repo_branch = $5,
    docker_host = $6,
    github_token_encrypted = $7,
    updated_at = now()
WHERE id = $1
RETURNING id, name, repo_owner, repo_name, repo_branch, docker_host, github_token_encrypted, discord_webhook_url, created_at, updated_at, user_id
`

type UpdateProjectParams struct {
	ID                   uuid.UUID `json:"id"`
	Name                 string    `json:"name"`
	RepoOwner            string    `json:"repo_owner"`
	RepoName             string    `json:"repo_name"`
	RepoBranch           string    `json:"repo_branch"`
	DockerHost           string    `json:"docker_host"`
	GithubTokenEncrypted *string   `json:"github_token_encrypted"`
}

func (q *Queries) UpdateProject(ctx context.Context, arg UpdateProjectParams) (Project, error) {
	row := q.db.QueryRow(ctx, updateProject,
		arg.ID,
		arg.Name,
		arg.RepoOwner,
		arg.RepoName,
		arg.RepoBranch,
		arg.DockerHost,
		arg.GithubTokenEncrypted,
	)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.RepoOwner,
		&i.RepoName,
		&i.RepoBranch,
		&i.DockerHost,
		&i.GithubTokenEncrypted,
		&i.DiscordWebhookUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.UserID,
	)
	return i, err
}
