// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: snapshots.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const createSnapshot = `-- name: CreateSnapshot :one
INSERT INTO snapshots (
    project_id,
    state_hash,
    live_state,
    declared_state
) VALUES (
    $1, $2, $3, $4
)
RETURNING id, project_id, state_hash, live_state, declared_state, taken_at
`

type CreateSnapshotParams struct {
	ProjectID     uuid.UUID `json:"project_id"`
	StateHash     string    `json:"state_hash"`
	LiveState     []byte    `json:"live_state"`
	DeclaredState []byte    `json:"declared_state"`
}

func (q *Queries) CreateSnapshot(ctx context.Context, arg CreateSnapshotParams) (Snapshot, error) {
	row := q.db.QueryRow(ctx, createSnapshot,
		arg.ProjectID,
		arg.StateHash,
		arg.LiveState,
		arg.DeclaredState,
	)
	var i Snapshot
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.StateHash,
		&i.LiveState,
		&i.DeclaredState,
		&i.TakenAt,
	)
	return i, err
}

const getLatestSnapshotByProject = `-- name: GetLatestSnapshotByProject :one
SELECT id, project_id, state_hash, live_state, declared_state, taken_at
FROM snapshots
WHERE project_id = $1
ORDER BY taken_at DESC
LIMIT 1
`

func (q *Queries) GetLatestSnapshotByProject(ctx context.Context, projectID uuid.UUID) (Snapshot, error) {
	row := q.db.QueryRow(ctx, getLatestSnapshotByProject, projectID)
	var i Snapshot
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.StateHash,
		&i.LiveState,
		&i.DeclaredState,
		&i.TakenAt,
	)
	return i, err
}
